import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full bg-red-100 md:max-w-2xl">
          <Navbar />
        </div>
      </main>
    </>
  );
};

export default Home;
