import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Posaunenchor Friedrichsthal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center">
        <div id="image-carusel" className="flex justify-center">
          <Image
            className="justify-center align-middle"
            src="/PoCho_Logo.png"
            width={700}
            height={700}
            alt="Logo"
          />
        </div>
        <div className="sticky top-0">
          <Navbar />
        </div>
        <div>
          <h1 className="text-center text-4xl">Herzlich Willkommen</h1>
          <p className="text-center">
            auf der Website des Posaunenchor Friedrichsthal
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Home;
