import Navbar from "~/components/navbar";
import { api } from "~/utils/api";
import Head from "next/head";
import { type User } from "@prisma/client";
import { SignInButton, useUser } from "@clerk/nextjs";
import { useState } from "react";
import { useRouter } from "next/router";
import { UserCard } from "@/src/components/userCard";

const AdminDashboard = () => {
  const usersQuery = api.user.getAll.useQuery();

  if (usersQuery.isError) {
    throw usersQuery.error;
  }
  if (!usersQuery.isSuccess) {
    return <div>Loading...</div>;
  }

  if (!usersQuery.data) {
    return <div>No users found</div>;
  }

  const users = usersQuery.data as User[];

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full">
        <div className="flex flex-col justify-center">
          <h1 className="text-center text-4xl">Admin Dashboard</h1>
          <div className="flex justify-center">
            <div className="flex flex-col justify-center">
              <h2 className="text-center text-2xl">Users</h2>
              <div className="grid grid-flow-row grid-cols-2 justify-between gap-5">
                {users.map((user) => (
                  <UserCard key={user.clerkId} {...user} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

const UserPage = () => {
  const [view, setView] = useState("admin");
  //get current user
  const userQuery = api.user.getSelf.useQuery();
  const router = useRouter();
  const { isSignedIn } = useUser();

  if (!isSignedIn) {
    //if not redirect to home page
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    return (
      <div>
        <h1>Not signed in</h1>
        <SignInButton />
      </div>
    );
  }

  if (userQuery.isSuccess) {
    if (!userQuery.data) {
      //if not redirect to register page
      // eslint-disable-next-line @typescript-eslint/no-floating-promises
      router.push("/register");
    }
  }

  const user = userQuery.data;
  if (!user) {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    router.push("/userSync");
    return <div>Redirecting...</div>;
  }

  return (
    <>
      <Head>
        <title>{user.displayName + "'s page"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full bg-red-100">
          <Navbar />
          <div className="flex justify-center">
            <div className="flex flex-col justify-center">
              <h1 className="text-center text-4xl">{user.displayName}</h1>
              <h2 className="text-center text-2xl">{user.email}</h2>
              {user.role == "ADMIN" && view === "admin" && <AdminDashboard />}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};
export default UserPage;
